const opportunities = [
  // ─── JOBS (6) ─────────────────────────────────────────────────────────────
  {
    type: "Jobs",
    title: "SDE Intern",
    organization: "Google",
    location: "Bangalore",
    difficulty: "Advanced",
    link: "https://careers.google.com",
    tags: ["DSA", "System Design", "Python", "FAANG"],
  },
  {
    type: "Jobs",
    title: "Frontend Engineer",
    organization: "Razorpay",
    location: "Remote",
    difficulty: "Intermediate",
    link: "https://razorpay.com/jobs",
    tags: ["React", "TypeScript", "Node.js"],
  },
  {
    type: "Jobs",
    title: "Backend Engineer",
    organization: "Zepto",
    location: "Mumbai",
    difficulty: "Intermediate",
    link: "https://zepto.in/careers",
    tags: ["Node.js", "MongoDB", "Redis", "Microservices"],
  },
  {
    type: "Jobs",
    title: "Full Stack Developer",
    organization: "Meesho",
    location: "Bangalore",
    difficulty: "Intermediate",
    link: "https://meesho.io/jobs",
    tags: ["React", "Node.js", "AWS"],
  },
  {
    type: "Jobs",
    title: "SDE-1",
    organization: "Flipkart",
    location: "Bangalore",
    difficulty: "Advanced",
    link: "https://flipkartcareers.com",
    tags: ["Java", "DSA", "Microservices", "FAANG-adjacent"],
  },
  {
    type: "Jobs",
    title: "Junior Software Engineer",
    organization: "CRED",
    location: "Bangalore",
    difficulty: "Intermediate",
    link: "https://cred.club/careers",
    tags: ["React", "TypeScript", "REST APIs"],
  },

  // ─── INTERNSHIPS (5) ──────────────────────────────────────────────────────
  {
    type: "Internships",
    title: "STEP Intern",
    organization: "Google",
    location: "Hyderabad",
    difficulty: "Intermediate",
    link: "https://careers.google.com/students",
    tags: ["CS Fundamentals", "FAANG", "Paid"],
  },
  {
    type: "Internships",
    title: "Google Summer of Code",
    organization: "Google",
    location: "Remote",
    difficulty: "Intermediate",
    reward: "$3,000–$6,600",
    link: "https://summerofcode.withgoogle.com",
    tags: ["Open Source", "GSoC", "Remote"],
  },
  {
    type: "Internships",
    title: "Microsoft Engage Mentorship",
    organization: "Microsoft",
    location: "Remote",
    difficulty: "Beginner",
    link: "https://microsoft.com/engage",
    tags: ["Azure", "React", "Mentorship"],
  },
  {
    type: "Internships",
    title: "Meta University Program",
    organization: "Meta",
    location: "Remote / Hyderabad",
    difficulty: "Intermediate",
    link: "https://metacareers.com",
    tags: ["React", "GraphQL", "FAANG"],
  },
  {
    type: "Internships",
    title: "Uber Star Internship",
    organization: "Uber",
    location: "Bangalore",
    difficulty: "Intermediate",
    link: "https://uber.com/careers",
    tags: ["System Design", "Python", "Paid"],
  },

  // ─── HACKATHONS (5) ───────────────────────────────────────────────────────
  {
    type: "Hackathons",
    title: "Smart India Hackathon 2025",
    organization: "Ministry of Education",
    location: "Pan India",
    difficulty: "Beginner",
    link: "https://sih.gov.in",
    tags: ["Innovation", "Team", "Government"],
  },
  {
    type: "Hackathons",
    title: "HackWithInfy",
    organization: "Infosys",
    location: "Online",
    difficulty: "Intermediate",
    link: "https://hackwithinfy.com",
    tags: ["Problem Solving", "Prize Money"],
  },
  {
    type: "Hackathons",
    title: "HackRx 6.0",
    organization: "Bajaj Finserv",
    location: "Online + Offline",
    difficulty: "Intermediate",
    reward: "₹30 Lakh prize pool",
    link: "https://hackrx.in",
    tags: ["FinTech", "AI", "Insurance"],
  },
  {
    type: "Hackathons",
    title: "Flipkart Grid 7.0",
    organization: "Flipkart",
    location: "Online",
    difficulty: "Advanced",
    link: "https://flipkartgrid.com",
    tags: ["E-commerce", "AI", "ML"],
  },
  {
    type: "Hackathons",
    title: "Amazon HackOn",
    organization: "Amazon",
    location: "Online",
    difficulty: "Intermediate",
    link: "https://hackon.amazon.in",
    tags: ["AWS", "Cloud", "Prize Money"],
  },

  // ─── CERTIFICATIONS (5) ───────────────────────────────────────────────────
  {
    type: "Certifications",
    title: "AWS Solutions Architect Associate",
    organization: "Amazon Web Services",
    location: "Online",
    difficulty: "Intermediate",
    link: "https://aws.amazon.com/certification/certified-solutions-architect-associate",
    tags: ["Cloud", "AWS", "Industry Standard"],
  },
  {
    type: "Certifications",
    title: "Meta Front-End Developer",
    organization: "Meta / Coursera",
    location: "Online",
    difficulty: "Beginner",
    link: "https://coursera.org/professional-certificates/meta-front-end-developer",
    tags: ["React", "CSS", "JavaScript"],
  },
  {
    type: "Certifications",
    title: "Google Cloud Associate Engineer",
    organization: "Google Cloud",
    location: "Online",
    difficulty: "Intermediate",
    link: "https://cloud.google.com/certification/cloud-engineer",
    tags: ["GCP", "DevOps", "Cloud"],
  },
  {
    type: "Certifications",
    title: "MongoDB Associate Developer",
    organization: "MongoDB",
    location: "Online",
    difficulty: "Beginner",
    link: "https://university.mongodb.com/certification",
    tags: ["MongoDB", "NoSQL", "Backend"],
  },
  {
    type: "Certifications",
    title: "Certified Kubernetes Administrator",
    organization: "CNCF",
    location: "Online",
    difficulty: "Advanced",
    link: "https://training.linuxfoundation.org/certification/certified-kubernetes-administrator-cka",
    tags: ["Kubernetes", "DevOps", "Containers"],
  },

  // ─── COMPETITIONS (5) ─────────────────────────────────────────────────────
  {
    type: "Competitions",
    title: "Google Code Jam",
    organization: "Google",
    location: "Online",
    difficulty: "Advanced",
    link: "https://codingcompetitions.withgoogle.com/codejam",
    tags: ["DSA", "Competitive Programming", "FAANG"],
  },
  {
    type: "Competitions",
    title: "ICPC India Regionals",
    organization: "ICPC Foundation",
    location: "Pan India",
    difficulty: "Advanced",
    link: "https://icpc.global",
    tags: ["Competitive Programming", "Algorithms", "Teams"],
  },
  {
    type: "Competitions",
    title: "LeetCode Weekly Contest",
    organization: "LeetCode",
    location: "Online",
    difficulty: "Intermediate",
    link: "https://leetcode.com/contest",
    tags: ["DSA", "Interview Prep", "Weekly"],
  },
  {
    type: "Competitions",
    title: "Codeforces Rounds",
    organization: "Codeforces",
    location: "Online",
    difficulty: "Intermediate",
    link: "https://codeforces.com",
    tags: ["CP", "DSA", "Regular"],
  },
  {
    type: "Competitions",
    title: "Facebook Hacker Cup",
    organization: "Meta",
    location: "Online",
    difficulty: "Advanced",
    link: "https://www.facebook.com/codingcompetitions/hacker-cup",
    tags: ["Algorithms", "FAANG", "Prize Money"],
  },
];

module.exports = opportunities;
