import React, { useEffect, useState } from "react";
import { roadmapService } from "../services/roadmapService";
import { RoadmapMonthlyGoal } from "../types";
import { useAuth } from "../context/AuthContext";
import { useSocket } from "../hooks/useSocket";
import { useAgent } from "../hooks/useAgent";
import { useToast } from "../context/ToastContext";
import { CheckSquare, Square, GitFork, ChevronDown, CheckCircle, Cpu, Activity, Terminal, Sparkles } from "lucide-react";

export const Roadmap: React.FC = () => {
  const { user, token } = useAuth();
  const { toast } = useToast();
  
  const [roadmap, setRoadmap] = useState<RoadmapMonthlyGoal[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [showConfigForm, setShowConfigForm] = useState(false);

  // Form States
  const [targetRole, setTargetRole] = useState(user?.targetRole || "Full Stack Developer");
  const [duration, setDuration] = useState("3 Months");
  const [intensity, setIntensity] = useState("Moderate");
  const [style, setStyle] = useState("Practical/Project-Based");
  const [customContext, setCustomContext] = useState("");

  // Live Agent Hooks
  const { agentSteps, clearSteps } = useSocket(token);
  const { runRoadmap, isRunning } = useAgent();

  const fetchRoadmap = async () => {
    try {
      const data = await roadmapService.getRoadmap();
      setRoadmap(data);
    } catch (err) {
      console.error("Failed to load roadmap:", err);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchRoadmap();
  }, []);

  const handleGenerateRoadmap = async (e?: React.FormEvent) => {
    if (e) e.preventDefault();
    clearSteps();
    toast("Spawning Roadmap Agent with your custom guidelines...", "info");
    
    const res = await runRoadmap({
      duration,
      intensity,
      style,
      targetRole,
      customContext
    });

    if (res) {
      toast("Roadmap generated successfully!", "success");
      setShowConfigForm(false);
      await fetchRoadmap();
    }
  };

  const handleToggleTask = async (monthIdx: number, weekIdx: number, taskId: string, taskTitle: string) => {
    try {
      const updated = await roadmapService.toggleTask(monthIdx, weekIdx, taskId);
      
      const targetTask = updated[monthIdx].weeks[weekIdx].tasks.find((t) => t.id === taskId);
      if (targetTask?.completed) {
        toast(`Completed: "${taskTitle}"`, "success");
      }
      
      const oldMonth = roadmap[monthIdx];
      const newMonth = updated[monthIdx];
      if (!oldMonth.completed && newMonth.completed) {
        toast(`Milestone achieved: "${newMonth.title}"!`, "success");
      }

      setRoadmap(updated);
    } catch {
      toast("Failed to update task", "error");
    }
  };

  const calculateMonthProgress = (month: RoadmapMonthlyGoal) => {
    let total = 0;
    let completed = 0;
    month.weeks.forEach((w) => {
      w.tasks.forEach((t) => {
        total++;
        if (t.completed) completed++;
      });
    });
    return total === 0 ? 0 : Math.round((completed / total) * 100);
  };

  if (isLoading) {
    return (
      <div className="flex flex-col gap-6 py-6 animate-pulse text-left">
        <div className="h-8 bg-muted rounded-xl w-48" />
        <div className="space-y-6">
          {[1, 2].map((i) => (
            <div key={i} className="h-64 bg-muted rounded-3xl" />
          ))}
        </div>
      </div>
    );
  }

  return (
    <div className="flex flex-col gap-8 text-left py-4 max-w-4xl mx-auto">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-border/20 pb-4">
        <div>
          <h1 className="text-3xl font-extrabold mb-1.5 tracking-tight bg-clip-text text-transparent bg-gradient-to-r from-violet-600 to-fuchsia-500 dark:from-violet-400 dark:to-fuchsia-400">
            Interactive Roadmap
          </h1>
          <p className="text-muted-foreground text-sm font-semibold">
            Custom learning tasks generated by your Roadmap Agent
          </p>
        </div>
        {roadmap.length > 0 && !showConfigForm && (
          <button
            onClick={() => setShowConfigForm(true)}
            className="px-6 py-3 rounded-2xl bg-violet-600 hover:bg-violet-500 text-white font-bold text-sm transition-all flex items-center justify-center gap-2 shadow-lg shadow-violet-500/10 shrink-0"
          >
            <Sparkles className="w-4 h-4" />
            <span>Customize & Regenerate</span>
          </button>
        )}
      </div>

      {/* Config Form / Parameters Card (Rendered when showConfigForm is true OR when roadmap is empty) */}
      {(showConfigForm || (roadmap.length === 0 && !isRunning)) && (
        <form onSubmit={handleGenerateRoadmap} className="glass p-6 sm:p-8 rounded-3xl border border-violet-500/20 space-y-5 flex flex-col text-xs font-semibold animate-fade-in">
          <div className="flex items-center gap-2 border-b border-border/40 pb-2.5 mb-2">
            <GitFork className="w-5 h-5 text-violet-500" />
            <h3 className="font-extrabold text-base text-foreground">Configure Roadmap Parameters</h3>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="flex flex-col gap-1.5">
              <label className="text-muted-foreground">Target Role / Goal Focus</label>
              <input
                type="text"
                value={targetRole}
                onChange={(e) => setTargetRole(e.target.value)}
                placeholder="e.g. Full Stack Developer, JEE IIT Rank"
                className="bg-background border border-border/85 rounded-2xl px-4 py-3.5 outline-none focus:border-violet-500 transition-colors font-semibold"
                required
              />
            </div>

            <div className="flex flex-col gap-1.5">
              <label className="text-muted-foreground">Duration (Months)</label>
              <select
                value={duration}
                onChange={(e) => setDuration(e.target.value)}
                className="bg-background border border-border/85 rounded-2xl px-4 py-3.5 outline-none focus:border-violet-500 transition-colors font-semibold appearance-none cursor-pointer"
              >
                <option value="1 Month">1 Month</option>
                <option value="2 Months">2 Months</option>
                <option value="3 Months">3 Months</option>
                <option value="6 Months">6 Months</option>
              </select>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="flex flex-col gap-1.5">
              <label className="text-muted-foreground">Study Intensity (Commitment)</label>
              <select
                value={intensity}
                onChange={(e) => setIntensity(e.target.value)}
                className="bg-background border border-border/85 rounded-2xl px-4 py-3.5 outline-none focus:border-violet-500 transition-colors font-semibold appearance-none cursor-pointer"
              >
                <option value="Light (5-10 hrs/week)">Light (5-10 hrs/week)</option>
                <option value="Moderate (15-20 hrs/week)">Moderate (15-20 hrs/week)</option>
                <option value="Intensive (30-40 hrs/week)">Intensive (30-40 hrs/week)</option>
              </select>
            </div>

            <div className="flex flex-col gap-1.5">
              <label className="text-muted-foreground">Study & Learning Style</label>
              <select
                value={style}
                onChange={(e) => setStyle(e.target.value)}
                className="bg-background border border-border/85 rounded-2xl px-4 py-3.5 outline-none focus:border-violet-500 transition-colors font-semibold appearance-none cursor-pointer"
              >
                <option value="Practical/Project-Based">Practical/Project-Based</option>
                <option value="Theoretical/NCERT-Focused">Theoretical/NCERT-Focused</option>
                <option value="Interview/DSA/MCQ-Focused">Interview/DSA/MCQ-Focused</option>
              </select>
            </div>
          </div>

          <div className="flex flex-col gap-1.5">
            <label className="text-muted-foreground">Custom Context Guidelines (Optional)</label>
            <textarea
              value={customContext}
              onChange={(e) => setCustomContext(e.target.value)}
              placeholder="e.g. Focus heavily on dynamic programming algorithms / I need organic chemistry reaction conversions details / focus on SQL queries"
              rows={3}
              className="bg-background border border-border/85 rounded-2xl p-4 outline-none focus:border-violet-500 transition-colors resize-none leading-relaxed font-semibold"
            />
          </div>

          <div className="flex gap-3.5 justify-end mt-2">
            {roadmap.length > 0 && (
              <button
                type="button"
                onClick={() => setShowConfigForm(false)}
                className="px-6 py-3.5 rounded-2xl border border-border/80 hover:bg-secondary/40 font-bold"
              >
                Cancel
              </button>
            )}
            <button
              type="submit"
              className="px-8 py-3.5 rounded-2xl bg-violet-600 hover:bg-violet-500 text-white font-bold transition-colors shadow-lg shadow-violet-500/10 flex items-center gap-1.5"
            >
              <Cpu className="w-4 h-4" />
              <span>Generate Custom Roadmap</span>
            </button>
          </div>
        </form>
      )}

      {/* Live Agent Console Panel */}
      {isRunning && (
        <div className="glass border border-border/80 rounded-3xl p-5 text-left flex flex-col gap-2.5 font-mono text-xs shadow-inner animate-fade-in">
          <div className="flex items-center justify-between border-b border-border/40 pb-2 text-[10px] text-muted-foreground uppercase font-bold tracking-wider">
            <div className="flex items-center gap-1.5">
              <Terminal className="w-4 h-4 text-violet-500" />
              <span>Roadmap Agent Console Log</span>
            </div>
            <span className="animate-pulse text-violet-500">Generating Syllabus...</span>
          </div>
          <div className="max-h-[160px] overflow-y-auto flex flex-col gap-1.5">
            {agentSteps.length === 0 ? (
              <div className="text-muted-foreground italic pl-2">Spawning agent and establishing websocket routing...</div>
            ) : (
              agentSteps.map((s, idx) => (
                <div key={idx} className="pb-1 last:border-none">
                  <span className="text-violet-500 font-bold mr-1.5">[{s.type.toUpperCase()}]</span>
                  <span className="text-foreground/80">{s.content}</span>
                </div>
              ))
            )}
          </div>
        </div>
      )}

      {/* Empty State message (Only if not running and not showing config form) */}
      {roadmap.length === 0 && !isRunning && !showConfigForm && (
        <div className="glass p-10 rounded-3xl border border-border/60 text-center max-w-md mx-auto my-10 flex flex-col items-center gap-4 animate-fade-in">
          <div className="w-12 h-12 rounded-xl bg-violet-500/10 flex items-center justify-center text-violet-500">
            <GitFork className="w-6 h-6" />
          </div>
          <h3 className="font-extrabold text-lg">No Roadmap Generated</h3>
          <p className="text-xs text-muted-foreground leading-relaxed font-semibold">
            Your personalized learning roadmap has not been built yet. Provide parameters above to spawn your AI Roadmap Agent.
          </p>
        </div>
      )}

      {/* Timeline Section */}
      {roadmap.length > 0 && !isRunning && !showConfigForm && (
        <div className="flex flex-col gap-10 relative pl-6 sm:pl-8 border-l border-border/40">
          {roadmap.map((month, monthIdx) => {
            const progress = calculateMonthProgress(month);
            return (
              <div key={month.month} className="relative">
                {/* Dot */}
                <div className={`absolute -left-11.5 sm:-left-13.5 top-1.5 w-6 h-6 rounded-full border-4 border-[#fafbfc] dark:border-[#0b0e14] flex items-center justify-center shrink-0 shadow-md ${
                  month.completed
                    ? "bg-emerald-500 text-white"
                    : progress > 0
                    ? "bg-violet-600 text-white"
                    : "bg-muted text-muted-foreground"
                }`}>
                  <div className="w-1.5 h-1.5 rounded-full bg-white" />
                </div>

                {/* Month Box */}
                <div className="glass rounded-3xl border border-border/60 p-6 flex flex-col gap-6 shadow-sm">
                  {/* Title info */}
                  <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-border/40">
                    <div className="text-left">
                      <span className="text-[10px] text-violet-500 font-bold uppercase tracking-wider">
                        {month.month}
                      </span>
                      <h3 className="font-extrabold text-lg text-foreground mt-0.5">
                        {month.title}
                      </h3>
                    </div>

                    <div className="flex items-center gap-3 shrink-0 text-xs font-semibold">
                      <span className="text-muted-foreground font-medium">Progress:</span>
                      <div className="w-24 bg-muted h-2 rounded-full overflow-hidden">
                        <div className="bg-violet-600 h-full transition-all duration-300" style={{ width: `${progress}%` }} />
                      </div>
                      <span className="text-foreground font-extrabold min-w-8 text-right">{progress}%</span>
                    </div>
                  </div>

                  {month.completed && (
                    <div className="p-3.5 rounded-2xl bg-emerald-500/5 border border-emerald-500/20 text-xs font-semibold text-emerald-600 dark:text-emerald-400 flex items-center gap-2.5">
                      <CheckCircle className="w-4.5 h-4.5 shrink-0 animate-bounce" />
                      <span>All tasks complete! Month milestone achieved.</span>
                    </div>
                  )}

                  {/* Weeks checklists */}
                  <div className="flex flex-col gap-5">
                    {month.weeks.map((week, weekIdx) => (
                      <div key={week.id} className="text-left">
                        <h4 className="font-extrabold text-sm text-foreground mb-3">
                          {week.title}
                        </h4>
                        
                        <div className="flex flex-col gap-2.5">
                          {week.tasks.map((task) => (
                            <button
                              key={task.id}
                              onClick={() => handleToggleTask(monthIdx, weekIdx, task.id, task.title)}
                              className="flex items-start gap-3 p-3 rounded-2xl border border-border/40 hover:bg-secondary/40 text-left text-xs font-semibold transition-all group w-full"
                            >
                              <span className="mt-0.5 shrink-0 text-violet-500 group-hover:scale-105 transition-transform">
                                {task.completed ? (
                                  <CheckSquare className="w-4.5 h-4.5 fill-current text-violet-600" />
                                ) : (
                                  <Square className="w-4.5 h-4.5 text-muted-foreground" />
                                )}
                              </span>
                              <span className={`leading-relaxed ${task.completed ? "text-muted-foreground line-through font-medium" : "text-foreground/90"}`}>
                                {task.title}
                              </span>
                            </button>
                          ))}
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
};
